on:
  push:
    tags:
      - 'v**'

jobs:
  publish:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - id: tag
        name: Get tag name
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

      - id: version
        name: Get version
        uses: SebRollen/toml-action@v1.0.0
        with:
          file: 'Cargo.toml'
          field: 'package.version'

      - id: compare
        name: Compare versions
        uses: madhead/semver-utils@latest
        with:
          version: ${{ steps.tag.outputs.app_version }}
          compare-to: ${{ steps.version.outputs.app_version }}

      - name: Debug
        shell: bash
        run: |
          echo "${{ steps.tag.outputs.app_version }}"
          echo "${{ steps.version.outputs.app_version }}"
          echo "${{ steps.version.outputs.comparison-result }}"

      - name: Check versions
        if: ${{ steps.version.outputs.comparison-result }} != =
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Cargo.toml version differs from release tag')

      - name: Publish
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
